https://github.com/AlexPshe
nataliamaslova/teamcity_test_framework pull request #1
Opened 2024-03-04 07:07 UTC by nataliamaslova

2024-03-11 08:34 UTC, AlexPshe requested changes
Привет, Наташа! 

Спасибо за выолненное задание, но оно было с подвохом 🌚

Что значит "покрыть такую-то функциональность тестами"? 

В реальном проекте, где мы один автоматизатор нам никто не даст готовые сценарии, 
а даже если и отдаст QA manual - их все равно придется перераспределить по определенным сценариям на уровне API. 

❗️золотое правило:

Про положительные сценарии ⬇️
На уровне API тестируются все положительные сценарии для разных типов данных 
(или классов эквивалентности и граничных значений)

Например: в имени проекта может быть такие-то символы, максимально такой-то длины. 

Про негативные сценарии ⬇️
На уровне API тестируются все негативные сценарии 
(как минимум для все описаных неуспешных статус кодов)

Например: два проекта с одним id не могут быть созданы.

В твоем домашнем задание я вижу только два простых теста, но не покрытие с учетами техник тест дизайна. Давай исправим и будет зачтено!

2024-03-25 21:55 UTC, nataliamaslova commented
Саша, привет!

Спасибо за мягкий пинок. Да, было понятно, что задание с подвохом.
Но было не понятно как к нему подступиться.
Переделала задание.

С нетерпением жду новых комментов!

2024-03-27 11:56 UTC, AlexPshe requested changes
Привет! 

Спасибо за выполненное задание - уже намного лучше 💪

Давай пофиксим комменты по оформлению и будет зачтено!

2024-03-27 11:56 UTC, AlexPshe commented on src/test/java/com/example/teamcity/api/CreateBuildConfigTest.java
> +        var expectedProjectName = "1000Symbol1000Symbol1000Symbol1000Symbol1000Symbol1000Symbol1000Symbol1000Symbol1000Symbol1000Symbol1000Symbol1000Symbol1000Symbol1000Symbol1000Symbol1000Symbol1000
Ты можешь использовать RandomStringUtils для генерации строки нужной длины, чтобы не делать код нечитаемым за счет 4000 символов :)

2024-03-27 11:56 UTC, AlexPshe commented on src/test/java/com/example/teamcity/api/CreateProjectTest.java
> +                .body(Matchers.containsString("No project found by name or internal/external id '"
Используй format, чтобы красиво складывать строку через placeholders

2024-03-27 16:39 UTC, nataliamaslova commented on src/test/java/com/example/teamcity/api/CreateBuildConfigTest.java
> +        var expectedProjectName = "1000Symbol1000Symbol1000Symbol1000Symbol1000Symbol1000Symbol1000Symbol1000Symbol1000Symbol1000Symbol1000Symbol1000Symbol1000Symbol1000Symbol1000Symbol1000Symbol1000
точно, спасибо!

2024-03-27 16:40 UTC, nataliamaslova commented on src/test/java/com/example/teamcity/api/CreateProjectTest.java
> +                .body(Matchers.containsString("No project found by name or internal/external id '"
поправила, спасибо!

2024-04-01 14:35 UTC, AlexPshe approved these changes
Отлично, теперь все зачтено!

2024-04-02 16:31 UTC, merged