Hometask 2
nataliamaslova/teamcity_test_framework pull request #2
Opened 2024-03-20 21:04 UTC by nataliamaslova

2024-04-01 14:40 UTC, AlexPshe requested changes
Привет! 

Спасибо за выполненное задание! 

На уровне UI все отлично, но нам всегда нужно убеждаться, что и на уровне API сущности были созданы или не созданы, как мы ожидаем. 

Давай добавим проекты и будет зачтено 💪

2024-04-01 14:40 UTC, AlexPshe commented on src/test/java/com/example/teamcity/ui/CreateNewProjectTest.java
> +                .getHeader().shouldNotHave(Condition.text(testData.getProject().getName()));
Необходимо также добавить проверку, что сущность не была создана в API

2024-04-01 14:40 UTC, AlexPshe commented on src/test/java/com/example/teamcity/ui/CreateNewProjectTest.java
> +        new ProjectsPage().open()
Необходимо также добавить проверку, что проект был создан в API

2024-04-01 14:40 UTC, AlexPshe commented on src/test/java/com/example/teamcity/ui/CreateBuildConfigTest.java
> +        new BuildSteps()
Необходимо также добавить проверку, что сущность не была создана в API

2024-04-01 14:40 UTC, AlexPshe commented on src/test/java/com/example/teamcity/ui/CreateBuildConfigTest.java
> +        softy.assertThat(pageTitle.contains(testData.getBuildType().getName()));
Необходимо также добавить проверку, что сущность была создана в API

2024-04-03 21:35 UTC, nataliamaslova commented on src/test/java/com/example/teamcity/ui/CreateNewProjectTest.java
> +                .getHeader().shouldNotHave(Condition.text(testData.getProject().getName()));
проверка добавлена

2024-04-03 21:35 UTC, nataliamaslova commented on src/test/java/com/example/teamcity/ui/CreateNewProjectTest.java
> +        new ProjectsPage().open()
проверка добавлена

2024-04-03 21:36 UTC, nataliamaslova commented on src/test/java/com/example/teamcity/ui/CreateBuildConfigTest.java
> +        new BuildSteps()
проверка добавлена

2024-04-03 21:37 UTC, nataliamaslova commented on src/test/java/com/example/teamcity/ui/CreateBuildConfigTest.java
> +        softy.assertThat(pageTitle.contains(testData.getBuildType().getName()));
проверка добавлена

2024-04-03 22:26 UTC, AlexPshe approved these changes
Огонь, теперь ровно то, что надо!

2024-04-04 09:49 UTC, merged