Hometask 4
nataliamaslova/teamcity_test_framework pull request #5
Opened 2024-04-14 18:09 UTC by nataliamaslova

2024-04-16 14:48 UTC, AlexPshe requested changes
Привет! 

В целом, все выглядит супер, как и ожидалось. 
Смущает только `thread.sleep()`, хотелось бы избежать засыпания. 

Давай попробуем проверять конкретное событие, которое мы ждем!

2024-04-16 14:48 UTC, AlexPshe commented on src/test/java/com/example/teamcity/api/AuthorizeAgentTest.java
> +        Thread.sleep(1000 * 20);
А что мы тут ждем? Возможно, стоит опираться на конкретное событие, которое мы ожидаем.

2024-04-18 20:08 UTC, nataliamaslova commented on src/test/java/com/example/teamcity/api/AuthorizeAgentTest.java
> +        Thread.sleep(1000 * 20);
Саша, привет!
Ждем когда появится неавторизованный агент
Awaitility задействовано

2024-04-18 21:03 UTC, AlexPshe approved these changes
Ура! Теперь зачтено!

2024-04-19 07:41 UTC, merged